services:
  app:
    image: konstkazan/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - "./app:/app"
      - node_modules:/app/node_modules
volumes:
  node_modules: